name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v1
        with:
          repository: RobinNagpal/dodao-onboarding-schemas
          token: ${{ secrets.DODAO_ONBOARDING_SCHEMAS_ACCESS_TOKEN }}
          persist-credentials: true
      - name: checkout submodule
        run: |
          git submodule init
          git submodule update
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, build, lint
        run: |
          yarn
          yarn run build
          yarn run lint
